/*
 * Copyright (c) 2025.
 * @Author: Rosbitskyy Ruslan
 * @email: rosbitskyy@gmail.com
 * @license Licensed under the MIT License (MIT)
 */

/*
 * IDLayr Passkeys
 * Base API definition for IDLayr Passkey Server 
 *
 * The version of the OpenAPI document: 1.0.12
 * Contact: help@idlayr.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AuthenticatorInfo
 */
public class AuthenticatorInfoTest {
    private final AuthenticatorInfo model = new AuthenticatorInfo();

    /**
     * Model tests for AuthenticatorInfo
     */
    @Test
    public void testAuthenticatorInfo() {
        // TODO: test AuthenticatorInfo
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'iconDark'
     */
    @Test
    public void iconDarkTest() {
        // TODO: test iconDark
    }

    /**
     * Test the property 'iconLight'
     */
    @Test
    public void iconLightTest() {
        // TODO: test iconLight
    }

    /**
     * Test the property 'fidoCertified'
     */
    @Test
    public void fidoCertifiedTest() {
        // TODO: test fidoCertified
    }

    /**
     * Test the property 'fidoCertifiedLevel'
     */
    @Test
    public void fidoCertifiedLevelTest() {
        // TODO: test fidoCertifiedLevel
    }

}
