/*
 * Copyright (c) 2025.
 * @Author: Rosbitskyy Ruslan
 * @email: rosbitskyy@gmail.com
 * @license Licensed under the MIT License (MIT)
 */

/*
 * IDLayr Passkeys
 * Base API definition for IDLayr Passkey Server 
 *
 * The version of the OpenAPI document: 1.0.12
 * Contact: help@idlayr.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.client.model.AuthenticatorInfo;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Passkey
 */
public class PasskeyTest {
    private final Passkey model = new Passkey();

    /**
     * Model tests for Passkey
     */
    @Test
    public void testPasskey() {
        // TODO: test Passkey
    }

    /**
     * Test the property 'credId'
     */
    @Test
    public void credIdTest() {
        // TODO: test credId
    }

    /**
     * Test the property 'counter'
     */
    @Test
    public void counterTest() {
        // TODO: test counter
    }

    /**
     * Test the property 'publicKey'
     */
    @Test
    public void publicKeyTest() {
        // TODO: test publicKey
    }

    /**
     * Test the property 'aaguid'
     */
    @Test
    public void aaguidTest() {
        // TODO: test aaguid
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'friendlyName'
     */
    @Test
    public void friendlyNameTest() {
        // TODO: test friendlyName
    }

    /**
     * Test the property 'lastUsed'
     */
    @Test
    public void lastUsedTest() {
        // TODO: test lastUsed
    }

    /**
     * Test the property 'attestationValid'
     */
    @Test
    public void attestationValidTest() {
        // TODO: test attestationValid
    }

    /**
     * Test the property 'authenticatorInfo'
     */
    @Test
    public void authenticatorInfoTest() {
        // TODO: test authenticatorInfo
    }

}
