/*
 * Copyright (c) 2025.
 * @Author: Rosbitskyy Ruslan
 * @email: rosbitskyy@gmail.com
 * @license Licensed under the MIT License (MIT)
 */

/*
 * IDLayr Passkeys
 * Base API definition for IDLayr Passkey Server 
 *
 * The version of the OpenAPI document: 1.0.12
 * Contact: help@idlayr.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WebAuthnMakeCredentialRequestAuthenticatorSelection
 */
public class WebAuthnMakeCredentialRequestAuthenticatorSelectionTest {
    private final WebAuthnMakeCredentialRequestAuthenticatorSelection model = new WebAuthnMakeCredentialRequestAuthenticatorSelection();

    /**
     * Model tests for WebAuthnMakeCredentialRequestAuthenticatorSelection
     */
    @Test
    public void testWebAuthnMakeCredentialRequestAuthenticatorSelection() {
        // TODO: test WebAuthnMakeCredentialRequestAuthenticatorSelection
    }

    /**
     * Test the property 'authenticatorAttachment'
     */
    @Test
    public void authenticatorAttachmentTest() {
        // TODO: test authenticatorAttachment
    }

    /**
     * Test the property 'requireResidentKey'
     */
    @Test
    public void requireResidentKeyTest() {
        // TODO: test requireResidentKey
    }

    /**
     * Test the property 'userVerification'
     */
    @Test
    public void userVerificationTest() {
        // TODO: test userVerification
    }

}
