/*
 * Copyright (c) 2025.
 * @Author: Rosbitskyy Ruslan
 * @email: rosbitskyy@gmail.com
 * @license Licensed under the MIT License (MIT)
 */

/*
 * IDLayr Passkeys
 * Base API definition for IDLayr Passkey Server 
 *
 * The version of the OpenAPI document: 1.0.12
 * Contact: help@idlayr.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WebAuthnMakeCredentialRequestExcludeCredentialsInner
 */
public class WebAuthnMakeCredentialRequestExcludeCredentialsInnerTest {
    private final WebAuthnMakeCredentialRequestExcludeCredentialsInner model = new WebAuthnMakeCredentialRequestExcludeCredentialsInner();

    /**
     * Model tests for WebAuthnMakeCredentialRequestExcludeCredentialsInner
     */
    @Test
    public void testWebAuthnMakeCredentialRequestExcludeCredentialsInner() {
        // TODO: test WebAuthnMakeCredentialRequestExcludeCredentialsInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'transports'
     */
    @Test
    public void transportsTest() {
        // TODO: test transports
    }

}
