/*
 * Copyright (c) 2025.
 * @Author: Rosbitskyy Ruslan
 * @email: rosbitskyy@gmail.com
 * @license Licensed under the MIT License (MIT)
 */

/*
 * IDLayr Passkeys
 * Base API definition for IDLayr Passkey Server 
 *
 * The version of the OpenAPI document: 1.0.12
 * Contact: help@idlayr.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.WebAuthnMakeCredentialRequestExcludeCredentialsInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WebAuthnGetAssertionRequest
 */
public class WebAuthnGetAssertionRequestTest {
    private final WebAuthnGetAssertionRequest model = new WebAuthnGetAssertionRequest();

    /**
     * Model tests for WebAuthnGetAssertionRequest
     */
    @Test
    public void testWebAuthnGetAssertionRequest() {
        // TODO: test WebAuthnGetAssertionRequest
    }

    /**
     * Test the property 'challenge'
     */
    @Test
    public void challengeTest() {
        // TODO: test challenge
    }

    /**
     * Test the property 'allowCredentials'
     */
    @Test
    public void allowCredentialsTest() {
        // TODO: test allowCredentials
    }

    /**
     * Test the property 'timeout'
     */
    @Test
    public void timeoutTest() {
        // TODO: test timeout
    }

    /**
     * Test the property 'userVerification'
     */
    @Test
    public void userVerificationTest() {
        // TODO: test userVerification
    }

}
