/*
 * Copyright (c) 2025.
 * @Author: Rosbitskyy Ruslan
 * @email: rosbitskyy@gmail.com
 * @license Licensed under the MIT License (MIT)
 */

/*
 * IDLayr Passkeys
 * Base API definition for IDLayr Passkey Server 
 *
 * The version of the OpenAPI document: 1.0.12
 * Contact: help@idlayr.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.WebAuthnMakeCredentialRequestAuthenticatorSelection;
import org.openapitools.client.model.WebAuthnMakeCredentialRequestExcludeCredentialsInner;
import org.openapitools.client.model.WebAuthnMakeCredentialRequestPubKeyCredParamsInner;
import org.openapitools.client.model.WebAuthnMakeCredentialRequestRp;
import org.openapitools.client.model.WebAuthnMakeCredentialRequestUser;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WebAuthnMakeCredentialRequest
 */
public class WebAuthnMakeCredentialRequestTest {
    private final WebAuthnMakeCredentialRequest model = new WebAuthnMakeCredentialRequest();

    /**
     * Model tests for WebAuthnMakeCredentialRequest
     */
    @Test
    public void testWebAuthnMakeCredentialRequest() {
        // TODO: test WebAuthnMakeCredentialRequest
    }

    /**
     * Test the property 'challenge'
     */
    @Test
    public void challengeTest() {
        // TODO: test challenge
    }

    /**
     * Test the property 'rp'
     */
    @Test
    public void rpTest() {
        // TODO: test rp
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

    /**
     * Test the property 'pubKeyCredParams'
     */
    @Test
    public void pubKeyCredParamsTest() {
        // TODO: test pubKeyCredParams
    }

    /**
     * Test the property 'timeout'
     */
    @Test
    public void timeoutTest() {
        // TODO: test timeout
    }

    /**
     * Test the property 'excludeCredentials'
     */
    @Test
    public void excludeCredentialsTest() {
        // TODO: test excludeCredentials
    }

    /**
     * Test the property 'authenticatorSelection'
     */
    @Test
    public void authenticatorSelectionTest() {
        // TODO: test authenticatorSelection
    }

    /**
     * Test the property 'attestation'
     */
    @Test
    public void attestationTest() {
        // TODO: test attestation
    }

}
