/*
 * Copyright (c) 2025.
 * @Author: Rosbitskyy Ruslan
 * @email: rosbitskyy@gmail.com
 * @license Licensed under the MIT License (MIT)
 */

/*
 * IDLayr Passkeys
 * Base API definition for IDLayr Passkey Server 
 *
 * The version of the OpenAPI document: 1.0.12
 * Contact: help@idlayr.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WebAuthnGetAssertionResponseResponse
 */
public class WebAuthnGetAssertionResponseResponseTest {
    private final WebAuthnGetAssertionResponseResponse model = new WebAuthnGetAssertionResponseResponse();

    /**
     * Model tests for WebAuthnGetAssertionResponseResponse
     */
    @Test
    public void testWebAuthnGetAssertionResponseResponse() {
        // TODO: test WebAuthnGetAssertionResponseResponse
    }

    /**
     * Test the property 'authenticatorData'
     */
    @Test
    public void authenticatorDataTest() {
        // TODO: test authenticatorData
    }

    /**
     * Test the property 'clientDataJSON'
     */
    @Test
    public void clientDataJSONTest() {
        // TODO: test clientDataJSON
    }

    /**
     * Test the property 'signature'
     */
    @Test
    public void signatureTest() {
        // TODO: test signature
    }

    /**
     * Test the property 'userHandle'
     */
    @Test
    public void userHandleTest() {
        // TODO: test userHandle
    }

}
