/*
 * Copyright (c) 2025.
 * @Author: Rosbitskyy Ruslan
 * @email: rosbitskyy@gmail.com
 * @license Licensed under the MIT License (MIT)
 */

/*
 * IDLayr Passkeys
 * Base API definition for IDLayr Passkey Server 
 *
 * The version of the OpenAPI document: 1.0.12
 * Contact: help@idlayr.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * WebAuthnMakeCredentialRequestAuthenticatorSelection
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-23T11:56:01.733301+03:00[Europe/Sofia]", comments = "Generator version: 7.7.0")
public class WebAuthnMakeCredentialRequestAuthenticatorSelection {
  public static final String SERIALIZED_NAME_AUTHENTICATOR_ATTACHMENT = "authenticatorAttachment";
  @SerializedName(SERIALIZED_NAME_AUTHENTICATOR_ATTACHMENT)
  private String authenticatorAttachment;

  public static final String SERIALIZED_NAME_REQUIRE_RESIDENT_KEY = "requireResidentKey";
  @SerializedName(SERIALIZED_NAME_REQUIRE_RESIDENT_KEY)
  private Boolean requireResidentKey;

  public static final String SERIALIZED_NAME_USER_VERIFICATION = "userVerification";
  @SerializedName(SERIALIZED_NAME_USER_VERIFICATION)
  private String userVerification;

  public WebAuthnMakeCredentialRequestAuthenticatorSelection() {
  }

  public WebAuthnMakeCredentialRequestAuthenticatorSelection authenticatorAttachment(String authenticatorAttachment) {
    this.authenticatorAttachment = authenticatorAttachment;
    return this;
  }

  /**
   * Get authenticatorAttachment
   * @return authenticatorAttachment
   */
  @javax.annotation.Nullable
  public String getAuthenticatorAttachment() {
    return authenticatorAttachment;
  }

  public void setAuthenticatorAttachment(String authenticatorAttachment) {
    this.authenticatorAttachment = authenticatorAttachment;
  }


  public WebAuthnMakeCredentialRequestAuthenticatorSelection requireResidentKey(Boolean requireResidentKey) {
    this.requireResidentKey = requireResidentKey;
    return this;
  }

  /**
   * Get requireResidentKey
   * @return requireResidentKey
   */
  @javax.annotation.Nullable
  public Boolean getRequireResidentKey() {
    return requireResidentKey;
  }

  public void setRequireResidentKey(Boolean requireResidentKey) {
    this.requireResidentKey = requireResidentKey;
  }


  public WebAuthnMakeCredentialRequestAuthenticatorSelection userVerification(String userVerification) {
    this.userVerification = userVerification;
    return this;
  }

  /**
   * Get userVerification
   * @return userVerification
   */
  @javax.annotation.Nullable
  public String getUserVerification() {
    return userVerification;
  }

  public void setUserVerification(String userVerification) {
    this.userVerification = userVerification;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebAuthnMakeCredentialRequestAuthenticatorSelection webAuthnMakeCredentialRequestAuthenticatorSelection = (WebAuthnMakeCredentialRequestAuthenticatorSelection) o;
    return Objects.equals(this.authenticatorAttachment, webAuthnMakeCredentialRequestAuthenticatorSelection.authenticatorAttachment) &&
        Objects.equals(this.requireResidentKey, webAuthnMakeCredentialRequestAuthenticatorSelection.requireResidentKey) &&
        Objects.equals(this.userVerification, webAuthnMakeCredentialRequestAuthenticatorSelection.userVerification);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authenticatorAttachment, requireResidentKey, userVerification);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebAuthnMakeCredentialRequestAuthenticatorSelection {\n");
    sb.append("    authenticatorAttachment: ").append(toIndentedString(authenticatorAttachment)).append("\n");
    sb.append("    requireResidentKey: ").append(toIndentedString(requireResidentKey)).append("\n");
    sb.append("    userVerification: ").append(toIndentedString(userVerification)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("authenticatorAttachment");
    openapiFields.add("requireResidentKey");
    openapiFields.add("userVerification");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WebAuthnMakeCredentialRequestAuthenticatorSelection
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WebAuthnMakeCredentialRequestAuthenticatorSelection.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WebAuthnMakeCredentialRequestAuthenticatorSelection is not found in the empty JSON string", WebAuthnMakeCredentialRequestAuthenticatorSelection.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!WebAuthnMakeCredentialRequestAuthenticatorSelection.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `WebAuthnMakeCredentialRequestAuthenticatorSelection` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("authenticatorAttachment") != null && !jsonObj.get("authenticatorAttachment").isJsonNull()) && !jsonObj.get("authenticatorAttachment").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `authenticatorAttachment` to be a primitive type in the JSON string but got `%s`", jsonObj.get("authenticatorAttachment").toString()));
      }
      if ((jsonObj.get("userVerification") != null && !jsonObj.get("userVerification").isJsonNull()) && !jsonObj.get("userVerification").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `userVerification` to be a primitive type in the JSON string but got `%s`", jsonObj.get("userVerification").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WebAuthnMakeCredentialRequestAuthenticatorSelection.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WebAuthnMakeCredentialRequestAuthenticatorSelection' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WebAuthnMakeCredentialRequestAuthenticatorSelection> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WebAuthnMakeCredentialRequestAuthenticatorSelection.class));

       return (TypeAdapter<T>) new TypeAdapter<WebAuthnMakeCredentialRequestAuthenticatorSelection>() {
           @Override
           public void write(JsonWriter out, WebAuthnMakeCredentialRequestAuthenticatorSelection value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WebAuthnMakeCredentialRequestAuthenticatorSelection read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WebAuthnMakeCredentialRequestAuthenticatorSelection given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WebAuthnMakeCredentialRequestAuthenticatorSelection
   * @throws IOException if the JSON string is invalid with respect to WebAuthnMakeCredentialRequestAuthenticatorSelection
   */
  public static WebAuthnMakeCredentialRequestAuthenticatorSelection fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WebAuthnMakeCredentialRequestAuthenticatorSelection.class);
  }

  /**
   * Convert an instance of WebAuthnMakeCredentialRequestAuthenticatorSelection to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

