/*
 * Copyright (c) 2025.
 * @Author: Rosbitskyy Ruslan
 * @email: rosbitskyy@gmail.com
 * @license Licensed under the MIT License (MIT)
 */

/*
 * IDLayr Passkeys
 * Base API definition for IDLayr Passkey Server 
 *
 * The version of the OpenAPI document: 1.0.12
 * Contact: help@idlayr.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.WebAuthnMakeCredentialRequestExcludeCredentialsInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * WebAuthnGetAssertionRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-23T11:56:01.733301+03:00[Europe/Sofia]", comments = "Generator version: 7.7.0")
public class WebAuthnGetAssertionRequest {
  public static final String SERIALIZED_NAME_CHALLENGE = "challenge";
  @SerializedName(SERIALIZED_NAME_CHALLENGE)
  private String challenge;

  public static final String SERIALIZED_NAME_ALLOW_CREDENTIALS = "allowCredentials";
  @SerializedName(SERIALIZED_NAME_ALLOW_CREDENTIALS)
  private List<WebAuthnMakeCredentialRequestExcludeCredentialsInner> allowCredentials = new ArrayList<>();

  public static final String SERIALIZED_NAME_TIMEOUT = "timeout";
  @SerializedName(SERIALIZED_NAME_TIMEOUT)
  private Integer timeout;

  public static final String SERIALIZED_NAME_USER_VERIFICATION = "userVerification";
  @SerializedName(SERIALIZED_NAME_USER_VERIFICATION)
  private String userVerification;

  public WebAuthnGetAssertionRequest() {
  }

  public WebAuthnGetAssertionRequest challenge(String challenge) {
    this.challenge = challenge;
    return this;
  }

  /**
   * Get challenge
   * @return challenge
   */
  @javax.annotation.Nullable
  public String getChallenge() {
    return challenge;
  }

  public void setChallenge(String challenge) {
    this.challenge = challenge;
  }


  public WebAuthnGetAssertionRequest allowCredentials(List<WebAuthnMakeCredentialRequestExcludeCredentialsInner> allowCredentials) {
    this.allowCredentials = allowCredentials;
    return this;
  }

  public WebAuthnGetAssertionRequest addAllowCredentialsItem(WebAuthnMakeCredentialRequestExcludeCredentialsInner allowCredentialsItem) {
    if (this.allowCredentials == null) {
      this.allowCredentials = new ArrayList<>();
    }
    this.allowCredentials.add(allowCredentialsItem);
    return this;
  }

  /**
   * Get allowCredentials
   * @return allowCredentials
   */
  @javax.annotation.Nullable
  public List<WebAuthnMakeCredentialRequestExcludeCredentialsInner> getAllowCredentials() {
    return allowCredentials;
  }

  public void setAllowCredentials(List<WebAuthnMakeCredentialRequestExcludeCredentialsInner> allowCredentials) {
    this.allowCredentials = allowCredentials;
  }


  public WebAuthnGetAssertionRequest timeout(Integer timeout) {
    this.timeout = timeout;
    return this;
  }

  /**
   * Get timeout
   * @return timeout
   */
  @javax.annotation.Nullable
  public Integer getTimeout() {
    return timeout;
  }

  public void setTimeout(Integer timeout) {
    this.timeout = timeout;
  }


  public WebAuthnGetAssertionRequest userVerification(String userVerification) {
    this.userVerification = userVerification;
    return this;
  }

  /**
   * Get userVerification
   * @return userVerification
   */
  @javax.annotation.Nullable
  public String getUserVerification() {
    return userVerification;
  }

  public void setUserVerification(String userVerification) {
    this.userVerification = userVerification;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebAuthnGetAssertionRequest webAuthnGetAssertionRequest = (WebAuthnGetAssertionRequest) o;
    return Objects.equals(this.challenge, webAuthnGetAssertionRequest.challenge) &&
        Objects.equals(this.allowCredentials, webAuthnGetAssertionRequest.allowCredentials) &&
        Objects.equals(this.timeout, webAuthnGetAssertionRequest.timeout) &&
        Objects.equals(this.userVerification, webAuthnGetAssertionRequest.userVerification);
  }

  @Override
  public int hashCode() {
    return Objects.hash(challenge, allowCredentials, timeout, userVerification);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebAuthnGetAssertionRequest {\n");
    sb.append("    challenge: ").append(toIndentedString(challenge)).append("\n");
    sb.append("    allowCredentials: ").append(toIndentedString(allowCredentials)).append("\n");
    sb.append("    timeout: ").append(toIndentedString(timeout)).append("\n");
    sb.append("    userVerification: ").append(toIndentedString(userVerification)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("challenge");
    openapiFields.add("allowCredentials");
    openapiFields.add("timeout");
    openapiFields.add("userVerification");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WebAuthnGetAssertionRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WebAuthnGetAssertionRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WebAuthnGetAssertionRequest is not found in the empty JSON string", WebAuthnGetAssertionRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!WebAuthnGetAssertionRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `WebAuthnGetAssertionRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("challenge") != null && !jsonObj.get("challenge").isJsonNull()) && !jsonObj.get("challenge").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `challenge` to be a primitive type in the JSON string but got `%s`", jsonObj.get("challenge").toString()));
      }
      if (jsonObj.get("allowCredentials") != null && !jsonObj.get("allowCredentials").isJsonNull()) {
        JsonArray jsonArrayallowCredentials = jsonObj.getAsJsonArray("allowCredentials");
        if (jsonArrayallowCredentials != null) {
          // ensure the json data is an array
          if (!jsonObj.get("allowCredentials").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `allowCredentials` to be an array in the JSON string but got `%s`", jsonObj.get("allowCredentials").toString()));
          }

          // validate the optional field `allowCredentials` (array)
          for (int i = 0; i < jsonArrayallowCredentials.size(); i++) {
            WebAuthnMakeCredentialRequestExcludeCredentialsInner.validateJsonElement(jsonArrayallowCredentials.get(i));
          };
        }
      }
      if ((jsonObj.get("userVerification") != null && !jsonObj.get("userVerification").isJsonNull()) && !jsonObj.get("userVerification").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `userVerification` to be a primitive type in the JSON string but got `%s`", jsonObj.get("userVerification").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WebAuthnGetAssertionRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WebAuthnGetAssertionRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WebAuthnGetAssertionRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WebAuthnGetAssertionRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<WebAuthnGetAssertionRequest>() {
           @Override
           public void write(JsonWriter out, WebAuthnGetAssertionRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WebAuthnGetAssertionRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WebAuthnGetAssertionRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WebAuthnGetAssertionRequest
   * @throws IOException if the JSON string is invalid with respect to WebAuthnGetAssertionRequest
   */
  public static WebAuthnGetAssertionRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WebAuthnGetAssertionRequest.class);
  }

  /**
   * Convert an instance of WebAuthnGetAssertionRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

