/*
 * Copyright (c) 2025.
 * @Author: Rosbitskyy Ruslan
 * @email: rosbitskyy@gmail.com
 * @license Licensed under the MIT License (MIT)
 */

/*
 * IDLayr Passkeys
 * Base API definition for IDLayr Passkey Server 
 *
 * The version of the OpenAPI document: 1.0.12
 * Contact: help@idlayr.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * WebAuthnMakeCredentialResponseResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-23T11:56:01.733301+03:00[Europe/Sofia]", comments = "Generator version: 7.7.0")
public class WebAuthnMakeCredentialResponseResponse {
  public static final String SERIALIZED_NAME_ATTESTATION_OBJECT = "attestationObject";
  @SerializedName(SERIALIZED_NAME_ATTESTATION_OBJECT)
  private String attestationObject;

  public static final String SERIALIZED_NAME_CLIENT_DATA_J_S_O_N = "clientDataJSON";
  @SerializedName(SERIALIZED_NAME_CLIENT_DATA_J_S_O_N)
  private String clientDataJSON;

  public WebAuthnMakeCredentialResponseResponse() {
  }

  public WebAuthnMakeCredentialResponseResponse attestationObject(String attestationObject) {
    this.attestationObject = attestationObject;
    return this;
  }

  /**
   * Get attestationObject
   * @return attestationObject
   */
  @javax.annotation.Nullable
  public String getAttestationObject() {
    return attestationObject;
  }

  public void setAttestationObject(String attestationObject) {
    this.attestationObject = attestationObject;
  }


  public WebAuthnMakeCredentialResponseResponse clientDataJSON(String clientDataJSON) {
    this.clientDataJSON = clientDataJSON;
    return this;
  }

  /**
   * Get clientDataJSON
   * @return clientDataJSON
   */
  @javax.annotation.Nullable
  public String getClientDataJSON() {
    return clientDataJSON;
  }

  public void setClientDataJSON(String clientDataJSON) {
    this.clientDataJSON = clientDataJSON;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebAuthnMakeCredentialResponseResponse webAuthnMakeCredentialResponseResponse = (WebAuthnMakeCredentialResponseResponse) o;
    return Objects.equals(this.attestationObject, webAuthnMakeCredentialResponseResponse.attestationObject) &&
        Objects.equals(this.clientDataJSON, webAuthnMakeCredentialResponseResponse.clientDataJSON);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attestationObject, clientDataJSON);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebAuthnMakeCredentialResponseResponse {\n");
    sb.append("    attestationObject: ").append(toIndentedString(attestationObject)).append("\n");
    sb.append("    clientDataJSON: ").append(toIndentedString(clientDataJSON)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("attestationObject");
    openapiFields.add("clientDataJSON");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WebAuthnMakeCredentialResponseResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WebAuthnMakeCredentialResponseResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WebAuthnMakeCredentialResponseResponse is not found in the empty JSON string", WebAuthnMakeCredentialResponseResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!WebAuthnMakeCredentialResponseResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `WebAuthnMakeCredentialResponseResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("attestationObject") != null && !jsonObj.get("attestationObject").isJsonNull()) && !jsonObj.get("attestationObject").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `attestationObject` to be a primitive type in the JSON string but got `%s`", jsonObj.get("attestationObject").toString()));
      }
      if ((jsonObj.get("clientDataJSON") != null && !jsonObj.get("clientDataJSON").isJsonNull()) && !jsonObj.get("clientDataJSON").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `clientDataJSON` to be a primitive type in the JSON string but got `%s`", jsonObj.get("clientDataJSON").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WebAuthnMakeCredentialResponseResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WebAuthnMakeCredentialResponseResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WebAuthnMakeCredentialResponseResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WebAuthnMakeCredentialResponseResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<WebAuthnMakeCredentialResponseResponse>() {
           @Override
           public void write(JsonWriter out, WebAuthnMakeCredentialResponseResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WebAuthnMakeCredentialResponseResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WebAuthnMakeCredentialResponseResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WebAuthnMakeCredentialResponseResponse
   * @throws IOException if the JSON string is invalid with respect to WebAuthnMakeCredentialResponseResponse
   */
  public static WebAuthnMakeCredentialResponseResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WebAuthnMakeCredentialResponseResponse.class);
  }

  /**
   * Convert an instance of WebAuthnMakeCredentialResponseResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

