/*
 * Copyright (c) 2025.
 * @Author: Rosbitskyy Ruslan
 * @email: rosbitskyy@gmail.com
 * @license Licensed under the MIT License (MIT)
 */

/*
 * IDLayr Passkeys
 * Base API definition for IDLayr Passkey Server 
 *
 * The version of the OpenAPI document: 1.0.12
 * Contact: help@idlayr.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Passkey;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PasskeysApi
 */
@Disabled
public class PasskeysApiTest {

    private final PasskeysApi api = new PasskeysApi();

    /**
     * Schedule passkey for deletion
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void usersUidPasskeysCredidDeleteTest() throws ApiException {
        String uid = null;
        String credid = null;
        api.usersUidPasskeysCredidDelete(uid, credid);
        // TODO: test validations
    }

    /**
     * Get specific passkey
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void usersUidPasskeysCredidGetTest() throws ApiException {
        String uid = null;
        String credid = null;
        Passkey response = api.usersUidPasskeysCredidGet(uid, credid);
        // TODO: test validations
    }

    /**
     * Update passkey friendly name
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void usersUidPasskeysCredidPutTest() throws ApiException {
        String uid = null;
        String credid = null;
        Passkey passkey = null;
        api.usersUidPasskeysCredidPut(uid, credid, passkey);
        // TODO: test validations
    }

    /**
     * List user passkeys
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void usersUidPasskeysGetTest() throws ApiException {
        String uid = null;
        List<Passkey> response = api.usersUidPasskeysGet(uid);
        // TODO: test validations
    }

}
