/*
 * Copyright (c) 2025.
 * @Author: Rosbitskyy Ruslan
 * @email: rosbitskyy@gmail.com
 * @license Licensed under the MIT License (MIT)
 */

/*
 * IDLayr Passkeys
 * Base API definition for IDLayr Passkey Server 
 *
 * The version of the OpenAPI document: 1.0.12
 * Contact: help@idlayr.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.User;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserApi
 */
@Disabled
public class UserApiTest {

    private final UserApi api = new UserApi();

    /**
     * List user objects
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void usersGetTest() throws ApiException {
        Integer limit = null;
        List<User> response = api.usersGet(limit);
        // TODO: test validations
    }

    /**
     * Create user object
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void usersPostTest() throws ApiException {
        User user = null;
        User response = api.usersPost(user);
        // TODO: test validations
    }

    /**
     * Delete user object
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void usersUidDeleteTest() throws ApiException {
        String uid = null;
        api.usersUidDelete(uid);
        // TODO: test validations
    }

    /**
     * Get user object
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void usersUidGetTest() throws ApiException {
        String uid = null;
        User response = api.usersUidGet(uid);
        // TODO: test validations
    }

    /**
     * Update user object
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void usersUidPutTest() throws ApiException {
        String uid = null;
        User user = null;
        api.usersUidPut(uid, user);
        // TODO: test validations
    }

}
